# Basic Information 
title: Marco Schouten
position:  ML researcher
affiliation: Aptiv PLC
affiliation_link: 
email: marco.j.schouten@gmail.com

# Search Engine Optimization (SEO)
keywords: marco schouten, schouten marco, marcoschouten, schoutenmarco
canonical: 
description: Marco Schouten is an ML researcher at Aptiv. His research lies in Machine Learning and High-definition (hd) maps.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
google_scholar: https://scholar.google.com/citations?user=SdQ_lIIAAAAJ
cv_link: https://marcoschouten.github.io/assets/CV-schouten.pdf
github_link: https://github.com/marcoschouten/
linkedin: https://www.linkedin.com/in/schoutenmarco/

# Images 
avatar: ./assets/img/profile.png
# favicon: ./assets/img/favicon.png
# favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
footnote: 
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: l3lesztPwCz-uXlzFI1Lt9SB3Ctz-pBQuMdYqnD0Ul8

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
